#image: thinca/vim

variables:
  GIT_SUBMODULE_STRATEGY: recursive


before_script:
  - apt update && apt install -y vim vim-gtk xvfb dbus-x11
    # libgtk2.0-dev libgtk-3-dev lsb-release
  - vim --version
  - type -a vim
  - uname -a
  - who

stuff:
  script:
    - git clone --depth 1 https://github.com/junegunn/vader.vim.git
    - export PATH="/usr/local/bin:$PATH"
    - export DISPLAY=:99.0
    - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
    - Xvfb :21 -screen 0 1024x768x24 +extension RANDR &
    - eval $(dbus-launch --sh-syntax);
    - mkdir local
    - DIR=$(pwd)/local
    - export PATH="$DIR/bin:$PATH"
    - pwd
    - sed -i 's/if has("gui_running")/if has("gui_running") || \&termguicolors/' /usr/share/vim/vim80/syntax/2html.vim || true
    - find /usr/share/vim -name '*2html.vim' || true
    - ln -s $(pwd) ~/.vim
    - ls -lA
    - ls -lA ~
    - ls -lA bundle
    - ls -lA bundle/vim-pathogen
    - rm -fv vimrc.html
    - >
      echo -e '\nq' | vim vimrc
      -c 'set bg=dark | color wwdc16 | redir @a | echo $VIMRUNTIME | color | set termguicolors? | set bg?  | redir END | 0put a | 0,.norm I"'
      -c "set bg=dark | let g:html_no_progress=1 |  runtime! syntax/2html.vim | w! | qa!";
    - touch vimrc.html
    - touch vimrc2.html
      #echo -e '\nq' | xvfb-run --auto-servernum gvim vimrc
      #-c "set bg=dark | color wwdc16 | redir @a | color | set termguicolors? | set bg?  | redir END | 0put a"
      #-c "set bg=dark | let g:html_no_progress=1 |  runtime! syntax/2html.vim | TOhtml | w! vimrc2.html | qa!";

      #--cmd "set termguicolors"
      #- echo -e '\nq' | gvim -R vimrc -c "set termguicolors | runtime! synatax/2html.vim | TOhtml | w! | qa!"
  artifacts:
    paths:
      - vimrc.html
      - vimrc2.html

#        - apt-get build-dep vim-gtk2 vim vim-gtk3 vim-athena
#        - git clone --depth 1 https://github.com/vim/vim.git
#        - cd vim
#        - # ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp
#        - ./configure --with-features=huge --enable-gui=athena --prefix=$DIR --disable-gtktest
#        - make
#        - sudo make install
#        - cd -


# vim:  sw=2 ts=2
