language: vim

git:
    depth: 3
    submodules: true

addons:
  apt:
    packages:
      - vim
      - vim-gtk
      - xvfb

env:
  global:
    - NO_AT_BRIDGE=1

before_script: |
  git clone --depth 1 https://github.com/junegunn/vader.vim.git
  export DISPLAY=:99.0
  sh -e /etc/init.d/xvfb start
  Xvfb :21 -screen 0 1024x768x24 +extension RANDR &
  eval $(dbus-launch --sh-syntax);
  sleep 3
  #
  #
  git clone --depth 1 https://github.com/vim/vim.git
  cd vim
  # ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp
  ./configure --with-features=huge --enable-gui=gtk3
  make
  sudo make install
  cd -


script: |
  gvim --version
  gvim vimrc -c "runtime! synatax/2html.vim | TOhtml | w | qa"

deploy:
  file: vimrc.html
  skip_cleanup: true

# vim: set ts=2 sw=2 :
