language: vim

git:
    depth: 3
    submodules: true

before_script: |
  git clone --depth 1 https://github.com/junegunn/vader.vim.git

script: |
  gvim vimrc -c "runtime! synatax/2html.vim | TOhtml | w | qa"

deploy:
  file: vimrc.html
  skip_cleanup: true
