language: vim

git:
    depth: 3
    submodules: true

addons:
  apt:
    packages:
      - vim
      - vim-gtk
      - xvfb

nv:
  global:
    - NO_AT_BRIDGE=1

before_script: |
  git clone --depth 1 https://github.com/junegunn/vader.vim.git
  export DISPLAY=:99.0
  sh -e /etc/init.d/xvfb start
  Xvfb :21 -screen 0 1024x768x24 +extension RANDR &
  eval $(dbus-launch --sh-syntax);
  sleep 3


script: |
  gvim vimrc -c "runtime! synatax/2html.vim | TOhtml | w | qa"

deploy:
  file: vimrc.html
  skip_cleanup: true
